### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by nabedge** [albatrosary/start-angular#11]
```
git clone git@github.com:albatrosary/start-angular.git
cd start-angular/
npm install
ng serve
```
I got error. see screenshot.

**Comment by nabedge** [comment]
![image](https://cloud.githubusercontent.com/assets/1396674/21637096/c3dd0492-d2a8-11e6-98db-96894697c30d.png)

**Comment by albatrosary** [comment]
Lazy load is a function supported from angular@2.3.1 (angular-cli@1.0.0-beta.23).
When writing this I used angular-cli@1.0.0-beta.22.
But when using Lazy Load we used angular-cli@1.0.0-beta.24.

Now push the module using angular-cli@1.0.0-beta.24, so please look.

Thank u!

**Comment by nabedge** [comment]
Just now, I do "git pull" and it looks good.
Thanks !
