### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by nabedge** [albatrosary/start-angular#8]
https://albatrosary.gitbooks.io/start-angular/content/%E3%83%93%E3%83%AB%E3%83%88%E3%82%A4%E3%83%B3%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96.html

```
formタグ名前を「demo」としテキストボックスの名前を「username」とします。
```
文章とサンプルコードとが違うような。

**Comment by albatrosary** [comment]
Hi, @nabedge

It is a simple mistake.

Thank you!
